name: CI WORKFLOW
on: push

jobs:
  ci-job:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Check files
        run: |
          pwd
          ls -la
          find . -name pom.xml

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build
        run: mvn compile

      - name: Test
        run: mvn test

      - name: Artifact
        run: mvn package

      - name: install aws cli
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          sudo apt-get update
          sudo apt-get install unzip -y
          unzip awscliv2.zip
          sudo ./aws/install
